FROM ubuntu:22.04

RUN apt-get update
RUN apt-get -y install gnupg
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list
RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install lsb-release mono-complete libc-bin lua5.4 libopenal1
RUN apt-get -y install libgtk2.0-0
RUN apt-get -y install libcanberra-gtk-module

ENV TZ=America/Detroit
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -y install ffmpeg libsm6 libxext6
RUN apt-get install libgl1-mesa-dri
RUN apt-get -y install x11-apps
RUN apt-get install -y --no-install-recommends alsa-base alsa-utils libsndfile1-dev

# FROM alpine:3.19
# RUN apk update
# RUN apk add gcompat openal-soft lua5.4 lsb-release-minimal procps libx11 libgdiplus mesa-gl libstdc++
# RUN apk add mono --update-cache --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
# RUN apk add font-terminus font-inconsolata font-dejavu font-noto font-noto-cjk font-awesome font-noto-extra

ADD . .